### PR TITLE
Allow for role selection

### PR DESCRIPTION
**Pull request by ChrisRut**
Rather than assume the first role, this will prompt the user to choose a role that they would like to assume.

The output of running the script with multiple roles looks something like this:
```
AWS role credentials 0.6.2

Author: Peter Gillard-Moss <pgillard@thoughtworks.com>
URL: <https://github.com/petergillardmoss/aws_role_credentials>

Please select the role you would like to assume:
[0] - arn:aws:iam::123456789012:role/Administrator
[1] - arn:aws:iam::123456789012:role/Developer
[2] - arn:aws:iam::098765432109:role/ReadOnly
Selection:


----------------------------------------------------------------
Your credentials have been stored in the AWS configuration file /Users/chrisrutter/.aws/credentials under the dev profile.
Note that they will expire at 2016-12-06T19:00:09Z.
You may safely rerun this script at any time to refresh your credentials.
To use this credential, call the AWS CLI with the --profile option (e.g. aws --profile dev ec2 describe-instances).
----------------------------------------------------------------
```

### CODE REVIEW

**Comment by tjbaker** [comment]
Hi Peter, hope can you take a look at this, we'd love to have it merged in.  Thanks!

**Comment by petergillardmoss** [comment]
Hi

Thanks for the pull request.

I've merged and will deploy to pypi soon.

**Comment by ChrisRut** [comment]
It appears this still hasn't been deployed to pypi.

**Comment by tjbaker** [comment]
I logged https://github.com/ThoughtWorksInc/aws_role_credentials/issues/9 as a reminder.

Thanks!

**Pull request merged**
